/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as BestaetigungRouteImport } from './routes/bestaetigung'
import { Route as BestellenRouteImport } from './routes/bestellen'
import { Route as BewertungenRouteImport } from './routes/bewertungen'
import { Route as CookieEinstellungenRouteImport } from './routes/cookie-einstellungen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HeizoelWissenRouteImport } from './routes/heizoel-wissen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LieferungZahlungRouteImport } from './routes/lieferung-zahlung'
import { Route as SitemapBundeslaenderDotxmlRouteImport } from './routes/sitemap-bundeslaender[.]xml'
import { Route as SitemapSeitenDotxmlRouteImport } from './routes/sitemap-seiten[.]xml'
import { Route as SitemapStaedteDotxmlRouteImport } from './routes/sitemap-staedte[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as HeizoelpreiseIndexRouteImport } from './routes/heizoelpreise.index'
import { Route as HeizoelpreiseCityRouteImport } from './routes/heizoelpreise.$city'
import { Route as PreisrechnerIndexRouteImport } from './routes/preisrechner.index'
import { Route as PreisrechnerErgebnisRouteImport } from './routes/preisrechner.ergebnis'
import { Route as HeizoelpreiseBundeslandStateRouteImport } from './routes/heizoelpreise.bundesland.$state'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const BestaetigungRoute = BestaetigungRouteImport.update({
  id: '/bestaetigung',
  path: '/bestaetigung',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellenRoute = BestellenRouteImport.update({
  id: '/bestellen',
  path: '/bestellen',
  getParentRoute: () => rootRouteImport,
} as any)
const BewertungenRoute = BewertungenRouteImport.update({
  id: '/bewertungen',
  path: '/bewertungen',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieEinstellungenRoute = CookieEinstellungenRouteImport.update({
  id: '/cookie-einstellungen',
  path: '/cookie-einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HeizoelWissenRoute = HeizoelWissenRouteImport.update({
  id: '/heizoel-wissen',
  path: '/heizoel-wissen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LieferungZahlungRoute = LieferungZahlungRouteImport.update({
  id: '/lieferung-zahlung',
  path: '/lieferung-zahlung',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBundeslaenderDotxmlRoute =
  SitemapBundeslaenderDotxmlRouteImport.update({
    id: '/sitemap-bundeslaender.xml',
    path: '/sitemap-bundeslaender.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapSeitenDotxmlRoute = SitemapSeitenDotxmlRouteImport.update({
  id: '/sitemap-seiten.xml',
  path: '/sitemap-seiten.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaedteDotxmlRoute = SitemapStaedteDotxmlRouteImport.update({
  id: '/sitemap-staedte.xml',
  path: '/sitemap-staedte.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const HeizoelpreiseIndexRoute = HeizoelpreiseIndexRouteImport.update({
  id: '/heizoelpreise/',
  path: '/heizoelpreise/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeizoelpreiseCityRoute = HeizoelpreiseCityRouteImport.update({
  id: '/heizoelpreise/$city',
  path: '/heizoelpreise/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const PreisrechnerIndexRoute = PreisrechnerIndexRouteImport.update({
  id: '/preisrechner/',
  path: '/preisrechner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreisrechnerErgebnisRoute = PreisrechnerErgebnisRouteImport.update({
  id: '/preisrechner/ergebnis',
  path: '/preisrechner/ergebnis',
  getParentRoute: () => rootRouteImport,
} as any)
const HeizoelpreiseBundeslandStateRoute =
  HeizoelpreiseBundeslandStateRouteImport.update({
    id: '/heizoelpreise/bundesland/$state',
    path: '/heizoelpreise/bundesland/$state',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/bestaetigung': typeof BestaetigungRoute
  '/bestellen': typeof BestellenRoute
  '/bewertungen': typeof BewertungenRoute
  '/cookie-einstellungen': typeof CookieEinstellungenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/heizoel-wissen': typeof HeizoelWissenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/lieferung-zahlung': typeof LieferungZahlungRoute
  '/sitemap-bundeslaender.xml': typeof SitemapBundeslaenderDotxmlRoute
  '/sitemap-seiten.xml': typeof SitemapSeitenDotxmlRoute
  '/sitemap-staedte.xml': typeof SitemapStaedteDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/widerruf': typeof WiderrufRoute
  '/heizoelpreise/$city': typeof HeizoelpreiseCityRoute
  '/preisrechner/ergebnis': typeof PreisrechnerErgebnisRoute
  '/heizoelpreise/': typeof HeizoelpreiseIndexRoute
  '/preisrechner/': typeof PreisrechnerIndexRoute
  '/heizoelpreise/bundesland/$state': typeof HeizoelpreiseBundeslandStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/bestaetigung': typeof BestaetigungRoute
  '/bestellen': typeof BestellenRoute
  '/bewertungen': typeof BewertungenRoute
  '/cookie-einstellungen': typeof CookieEinstellungenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/heizoel-wissen': typeof HeizoelWissenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/lieferung-zahlung': typeof LieferungZahlungRoute
  '/sitemap-bundeslaender.xml': typeof SitemapBundeslaenderDotxmlRoute
  '/sitemap-seiten.xml': typeof SitemapSeitenDotxmlRoute
  '/sitemap-staedte.xml': typeof SitemapStaedteDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/widerruf': typeof WiderrufRoute
  '/heizoelpreise/$city': typeof HeizoelpreiseCityRoute
  '/preisrechner/ergebnis': typeof PreisrechnerErgebnisRoute
  '/heizoelpreise': typeof HeizoelpreiseIndexRoute
  '/preisrechner': typeof PreisrechnerIndexRoute
  '/heizoelpreise/bundesland/$state': typeof HeizoelpreiseBundeslandStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/bestaetigung': typeof BestaetigungRoute
  '/bestellen': typeof BestellenRoute
  '/bewertungen': typeof BewertungenRoute
  '/cookie-einstellungen': typeof CookieEinstellungenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/heizoel-wissen': typeof HeizoelWissenRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/lieferung-zahlung': typeof LieferungZahlungRoute
  '/sitemap-bundeslaender.xml': typeof SitemapBundeslaenderDotxmlRoute
  '/sitemap-seiten.xml': typeof SitemapSeitenDotxmlRoute
  '/sitemap-staedte.xml': typeof SitemapStaedteDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/widerruf': typeof WiderrufRoute
  '/heizoelpreise/$city': typeof HeizoelpreiseCityRoute
  '/preisrechner/ergebnis': typeof PreisrechnerErgebnisRoute
  '/heizoelpreise/': typeof HeizoelpreiseIndexRoute
  '/preisrechner/': typeof PreisrechnerIndexRoute
  '/heizoelpreise/bundesland/$state': typeof HeizoelpreiseBundeslandStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/bestaetigung'
    | '/bestellen'
    | '/bewertungen'
    | '/cookie-einstellungen'
    | '/datenschutz'
    | '/faq'
    | '/heizoel-wissen'
    | '/impressum'
    | '/kontakt'
    | '/lieferung-zahlung'
    | '/sitemap-bundeslaender.xml'
    | '/sitemap-seiten.xml'
    | '/sitemap-staedte.xml'
    | '/sitemap.xml'
    | '/widerruf'
    | '/heizoelpreise/$city'
    | '/preisrechner/ergebnis'
    | '/heizoelpreise/'
    | '/preisrechner/'
    | '/heizoelpreise/bundesland/$state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/bestaetigung'
    | '/bestellen'
    | '/bewertungen'
    | '/cookie-einstellungen'
    | '/datenschutz'
    | '/faq'
    | '/heizoel-wissen'
    | '/impressum'
    | '/kontakt'
    | '/lieferung-zahlung'
    | '/sitemap-bundeslaender.xml'
    | '/sitemap-seiten.xml'
    | '/sitemap-staedte.xml'
    | '/sitemap.xml'
    | '/widerruf'
    | '/heizoelpreise/$city'
    | '/preisrechner/ergebnis'
    | '/heizoelpreise'
    | '/preisrechner'
    | '/heizoelpreise/bundesland/$state'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/bestaetigung'
    | '/bestellen'
    | '/bewertungen'
    | '/cookie-einstellungen'
    | '/datenschutz'
    | '/faq'
    | '/heizoel-wissen'
    | '/impressum'
    | '/kontakt'
    | '/lieferung-zahlung'
    | '/sitemap-bundeslaender.xml'
    | '/sitemap-seiten.xml'
    | '/sitemap-staedte.xml'
    | '/sitemap.xml'
    | '/widerruf'
    | '/heizoelpreise/$city'
    | '/preisrechner/ergebnis'
    | '/heizoelpreise/'
    | '/preisrechner/'
    | '/heizoelpreise/bundesland/$state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  BestaetigungRoute: typeof BestaetigungRoute
  BestellenRoute: typeof BestellenRoute
  BewertungenRoute: typeof BewertungenRoute
  CookieEinstellungenRoute: typeof CookieEinstellungenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FaqRoute: typeof FaqRoute
  HeizoelWissenRoute: typeof HeizoelWissenRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LieferungZahlungRoute: typeof LieferungZahlungRoute
  SitemapBundeslaenderDotxmlRoute: typeof SitemapBundeslaenderDotxmlRoute
  SitemapSeitenDotxmlRoute: typeof SitemapSeitenDotxmlRoute
  SitemapStaedteDotxmlRoute: typeof SitemapStaedteDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WiderrufRoute: typeof WiderrufRoute
  HeizoelpreiseCityRoute: typeof HeizoelpreiseCityRoute
  PreisrechnerErgebnisRoute: typeof PreisrechnerErgebnisRoute
  HeizoelpreiseIndexRoute: typeof HeizoelpreiseIndexRoute
  PreisrechnerIndexRoute: typeof PreisrechnerIndexRoute
  HeizoelpreiseBundeslandStateRoute: typeof HeizoelpreiseBundeslandStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestaetigung': {
      id: '/bestaetigung'
      path: '/bestaetigung'
      fullPath: '/bestaetigung'
      preLoaderRoute: typeof BestaetigungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellen': {
      id: '/bestellen'
      path: '/bestellen'
      fullPath: '/bestellen'
      preLoaderRoute: typeof BestellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewertungen': {
      id: '/bewertungen'
      path: '/bewertungen'
      fullPath: '/bewertungen'
      preLoaderRoute: typeof BewertungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-einstellungen': {
      id: '/cookie-einstellungen'
      path: '/cookie-einstellungen'
      fullPath: '/cookie-einstellungen'
      preLoaderRoute: typeof CookieEinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heizoel-wissen': {
      id: '/heizoel-wissen'
      path: '/heizoel-wissen'
      fullPath: '/heizoel-wissen'
      preLoaderRoute: typeof HeizoelWissenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieferung-zahlung': {
      id: '/lieferung-zahlung'
      path: '/lieferung-zahlung'
      fullPath: '/lieferung-zahlung'
      preLoaderRoute: typeof LieferungZahlungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-bundeslaender.xml': {
      id: '/sitemap-bundeslaender.xml'
      path: '/sitemap-bundeslaender.xml'
      fullPath: '/sitemap-bundeslaender.xml'
      preLoaderRoute: typeof SitemapBundeslaenderDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-seiten.xml': {
      id: '/sitemap-seiten.xml'
      path: '/sitemap-seiten.xml'
      fullPath: '/sitemap-seiten.xml'
      preLoaderRoute: typeof SitemapSeitenDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-staedte.xml': {
      id: '/sitemap-staedte.xml'
      path: '/sitemap-staedte.xml'
      fullPath: '/sitemap-staedte.xml'
      preLoaderRoute: typeof SitemapStaedteDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heizoelpreise/': {
      id: '/heizoelpreise/'
      path: '/heizoelpreise'
      fullPath: '/heizoelpreise/'
      preLoaderRoute: typeof HeizoelpreiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heizoelpreise/$city': {
      id: '/heizoelpreise/$city'
      path: '/heizoelpreise/$city'
      fullPath: '/heizoelpreise/$city'
      preLoaderRoute: typeof HeizoelpreiseCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preisrechner/': {
      id: '/preisrechner/'
      path: '/preisrechner'
      fullPath: '/preisrechner/'
      preLoaderRoute: typeof PreisrechnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preisrechner/ergebnis': {
      id: '/preisrechner/ergebnis'
      path: '/preisrechner/ergebnis'
      fullPath: '/preisrechner/ergebnis'
      preLoaderRoute: typeof PreisrechnerErgebnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heizoelpreise/bundesland/$state': {
      id: '/heizoelpreise/bundesland/$state'
      path: '/heizoelpreise/bundesland/$state'
      fullPath: '/heizoelpreise/bundesland/$state'
      preLoaderRoute: typeof HeizoelpreiseBundeslandStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  BestaetigungRoute: BestaetigungRoute,
  BestellenRoute: BestellenRoute,
  BewertungenRoute: BewertungenRoute,
  CookieEinstellungenRoute: CookieEinstellungenRoute,
  DatenschutzRoute: DatenschutzRoute,
  FaqRoute: FaqRoute,
  HeizoelWissenRoute: HeizoelWissenRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LieferungZahlungRoute: LieferungZahlungRoute,
  SitemapBundeslaenderDotxmlRoute: SitemapBundeslaenderDotxmlRoute,
  SitemapSeitenDotxmlRoute: SitemapSeitenDotxmlRoute,
  SitemapStaedteDotxmlRoute: SitemapStaedteDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WiderrufRoute: WiderrufRoute,
  HeizoelpreiseCityRoute: HeizoelpreiseCityRoute,
  PreisrechnerErgebnisRoute: PreisrechnerErgebnisRoute,
  HeizoelpreiseIndexRoute: HeizoelpreiseIndexRoute,
  PreisrechnerIndexRoute: PreisrechnerIndexRoute,
  HeizoelpreiseBundeslandStateRoute: HeizoelpreiseBundeslandStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
